# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [ pull_request, push, workflow_dispatch ]

jobs:
  build-j21:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3.4.2
      - name: setup jdk 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build 1.21
        run: ./gradlew :v1_21:build

      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./**/build/libs/*.jar
  build-j17:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3.4.2
      - name: setup jdk 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build 1.20
        run: ./gradlew :v1_20:build

      - name: build 1.20.4
        run: ./gradlew :v1_20_4:build

      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./**/build/libs/*.jar
